name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2024-01-01
        components: rustfmt, clippy
    - name: Check code format
      continue-on-error: true
      run: cd kernel && cargo fmt -- --check
    - name: Cargo check kernel
      continue-on-error: true
      run: cd kernel && cargo check
